### ISSUE TITLE
I just tried cloning this repository

### ISSUE THREAD

**Issue by DoctorWho8** [WildernessLabs/Netduino_Hardware#1]
Hello!
I just tried cloning this repository. And just when I thought the process succeeded it caused my client to throw up an disturbing objection that was too complicated to render here. Something about the settings at the host being out of whack with the ones constructed during the checkout/clone process. To me it looked as if the metadata had gotten out of whack somehow.

**Comment by NevynUK** [comment]
This repository clones OK on both Windows and Mac.

If you are still having problems then can I suggest checking the help for your client software for assistance.

Regards,
Mark
